export const blogs = [
    {
        id: '1',
        title: 'Blog 1: Introduction to Vue.js',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'This is an introduction to Vue.js blog post.This is an introduction to Vue.js blog post.This is an introduction to Vue.js blog post.This is an introduction to Vue.js blog post.',
        date: '2024-04-15',
    },
    {
        id: '2',
        title: 'Blog 2: Styling Tips for Angular Applications',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Discover effective styling tips for Angular applications.',
        date: '2024-05-01',
    },
    {
        id: '3',
        title: 'Blog 3: State Management with Redux',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Learn about state management using Redux in your projects.',
        date: '2024-05-15',
    },
    {
        id: '4',
        title: 'Blog 4: Exploring Svelte Framework',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Explore the features of the Svelte framework for frontend development.',
        date: '2024-06-01',
    },
    {
        id: '5',
        title: 'Blog 5: Getting Started with GraphQL',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Get started with GraphQL and its integration in modern web development.',
        date: '2024-06-15',
    },
    {
        id: '6',
        title: 'Blog 6: Effective Unit Testing in Jest',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Learn effective strategies for unit testing using Jest.',
        date: '2024-07-01',
    },
    {
        id: '7',
        title: 'Blog 7: Advanced CSS Techniques',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Master advanced CSS techniques for creating stunning web designs.',
        date: '2024-07-15',
    },
    {
        id: '8',
        title: 'Blog 8: JavaScript ES6 Features',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Explore the features and enhancements introduced in JavaScript ES6.',
        date: '2024-08-01',
    },
    {
        id: '9',
        title: 'Blog 9: Frontend Security Best Practices',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Follow the best practices for ensuring security in frontend development.',
        date: '2024-08-15',
    },
    {
        id: '10',
        title: 'Blog 10: Mobile-First Design Principles',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Learn the principles of designing for a mobile-first user experience.',
        date: '2024-09-01',
    },
    {
        id: '11',
        title: 'Blog 11: Responsive Web Design Strategies',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Explore strategies for creating responsive web designs.',
        date: '2024-09-15',
    },
    {
        id: '12',
        title: 'Blog 12: Advanced Frontend Frameworks',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Discover advanced frontend frameworks for efficient development.',
        date: '2024-10-01',
    },
    {
        id: '13',
        title: 'Blog 13: Serverless Architecture with AWS Lambda',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Learn about serverless architecture using AWS Lambda services.',
        date: '2024-10-15',
    },
    {
        id: '14',
        title: 'Blog 14: Progressive Web Apps (PWAs)',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Understand the concept and development of Progressive Web Apps.',
        date: '2024-11-01',
    },
    {
        id: '15',
        title: 'Blog 15: Optimizing Website Performance',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Explore techniques for optimizing website performance.',
        date: '2024-11-15',
    },
    {
        id: '16',
        title: 'Blog 16: Enhancing UX with Animation',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Learn how to enhance user experience through effective animation.',
        date: '2024-12-01',
    },
    {
        id: '17',
        title: 'Blog 17: Introduction to Docker Containers',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Get an introduction to using Docker containers for application deployment.',
        date: '2024-12-15',
    },
    {
        id: '18',
        title: 'Blog 18: Modern Database Technologies',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Explore modern database technologies for scalable applications.',
        date: '2025-01-01',
    },
    {
        id: '19',
        title: 'Blog 19: Effective Cross-Browser Testing',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Learn strategies for conducting effective cross-browser testing.',
        date: '2025-01-15',
    },
    {
        id: '20',
        title: 'Blog 20: Mastering DevOps Practices',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Master key DevOps practices for seamless development and deployment.',
        date: '2025-02-01',
    }, {
        id: '21',
        title: 'Blog 21: Advanced Backend Development Techniques',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Explore advanced techniques in backend development for scalable applications.',
        date: '2025-02-15',
    },
    {
        id: '22',
        title: 'Blog 22: CI/CD Pipelines with Jenkins',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Implement Continuous Integration and Continuous Delivery pipelines using Jenkins.',
        date: '2025-03-01',
    },
    {
        id: '23',
        title: 'Blog 23: Microservices Architecture Patterns',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Understand different patterns in Microservices Architecture for modern applications.',
        date: '2025-03-15',
    },
    {
        id: '24',
        title: 'Blog 24: Cloud Computing Services Comparison',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Compare various cloud computing services for hosting and scaling your applications.',
        date: '2025-04-01',
    },
    {
        id: '25',
        title: 'Blog 25: Advanced React Native Development',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Dive into advanced topics in React Native development for cross-platform mobile apps.',
        date: '2025-04-15',
    }, {
        id: '26',
        title: 'Blog 26: Machine Learning in Web Development',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Explore the integration of machine learning in web development for intelligent applications.',
        date: '2025-05-01',
    },
    {
        id: '27',
        title: 'Blog 27: Progressive Enhancement in Web Design',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Understand the concept of progressive enhancement for creating robust and accessible web designs.',
        date: '2025-05-15',
    },
    {
        id: '28',
        title: 'Blog 28: Advanced TypeScript Features',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Discover advanced features and patterns in TypeScript for scalable and maintainable code.',
        date: '2025-06-01',
    },
    {
        id: '29',
        title: 'Blog 29: Design Systems for Consistent UI',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Implement design systems to achieve consistent and scalable user interfaces in your projects.',
        date: '2025-06-15',
    },
    {
        id: '30',
        title: 'Blog 30: Cross-Platform Mobile Development with Flutter',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Get started with cross-platform mobile development using the Flutter framework.',
        date: '2025-07-01',
    },
    {
        id: '30',
        title: 'Blog 30: Cross-Platform Mobile Development with Flutter',
        image: '/imgBlogs/anhtest.jpg',
        excerpt: 'Get started with cross-platform mobile development using the Flutter framework.',
        date: '2025-07-01',
    },
];
